### PR TITLE
fix(exceptions): wrapping method calls in try/catch

### PR DESCRIPTION
**Pull request by milos1290**

### CODE REVIEW

**Comment by benmarten** [comment]
Yes, I agree. It should be a simple api call delivering the exception....

**Comment by milos1290** [comment]
I'll see what i can do, the problem is that macro is private.

**Comment by milos1290** [comment]
@alexisoyama our internal calls are already wrapped with try/catch. To support logging i'll have to expose some of the internal stuff to segment integration.

**Comment by alexisoyama** [comment]
You're right. Since we are calling only the public methods anyway, exceptions should be caught by the SDK. I wonder why it didn't though...

I'm not sure if we need this commit then. @benmarten ?

**Comment by milos1290** [comment]
@alexisoyama i would have this also merged, in case something crashes before calling public API. If there is a crash in SDK we will have exceptions logged.

**Comment by alexisoyama** [comment]
Actually I think we can use internal here because we have the core SDK as dependencies. Similar to Leanplum-Location.

**Pull request merged**
